<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AttachmentController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CustomerApiController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\PasswordSetupController;
use App\Http\Controllers\ProfileController;

/*
|--------------------------------------------------------------------------
| Jarvies Portal Routes
|--------------------------------------------------------------------------
|
| Clean, organized routing structure for Jarvies frontend portal
| All routes communicate with Ecosystem API backend
|
*/

// ==================== PUBLIC LEGAL PAGES ====================
Route::get('/terms', fn() => view('legal.terms'))->name('legal.terms');
Route::get('/privacy', fn() => view('legal.privacy'))->name('legal.privacy');

// ==================== GUEST ROUTES ====================
Route::middleware('jarvies.guest')->group(function () {
    Route::get('/', [AuthController::class, 'showLogin'])->name('home');
    Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
    Route::post('/login', [AuthController::class, 'login']);
});

// ==================== PASSWORD SETUP & RESET ROUTES ====================
Route::get('/password/check-email', [PasswordSetupController::class, 'showCheckEmail'])->name('password-setup.check-email');
Route::get('/password/change', [PasswordSetupController::class, 'showChangePassword'])->name('password-setup.change');
Route::post('/password/change', [PasswordSetupController::class, 'submitChangePassword'])->name('password-setup.submit');
Route::get('/password/forgot', [PasswordSetupController::class, 'showForgotPassword'])->name('password-setup.forgot');
Route::post('/password/forgot', [PasswordSetupController::class, 'submitForgotPassword'])->name('password-setup.forgot.submit');

// ==================== ECOSYSTEM-COMPATIBLE ALIASES ====================
// EcoSystem sends setup/reset emails with /change-password?token=... links.
// These aliases let the same cp_token work whether the link came from
// EcoSystem or was generated by JARVIES itself.
Route::get('/change-password', [PasswordSetupController::class, 'showChangePassword'])->name('password-setup.change.alias');
Route::post('/change-password', [PasswordSetupController::class, 'submitChangePassword'])->name('password-setup.submit.alias');

// ==================== AUTHENTICATED ROUTES ====================
Route::middleware('jarvies.auth')->group(function () {
    
    // ==================== AUTHENTICATION ====================
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    
    // ==================== DASHBOARD ====================
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    
    // ==================== TICKETS ====================
    Route::prefix('tickets')->name('tickets.')->group(function () {
        // List & Views
        Route::get('/', [TicketController::class, 'index'])->name('index');
        Route::get('/create', [TicketController::class, 'create'])->name('create');
        Route::get('/{id}', [TicketController::class, 'show'])->name('show')->whereNumber('id');
        
        // CRUD Actions
        Route::post('/', [TicketController::class, 'store'])->name('store');
        Route::put('/{id}', [TicketController::class, 'update'])->name('update')->whereNumber('id');
        Route::delete('/{id}', [TicketController::class, 'destroy'])->name('destroy')->whereNumber('id');
        
        // AJAX API Endpoints
        Route::get('/ajax/fetch', [TicketController::class, 'getTickets'])->name('ajax.fetch');
        Route::get('/staging', [TicketController::class, 'getStagingTickets'])->name('staging');
        Route::get('/staging/{id}', [TicketController::class, 'showStaging'])->name('staging.show')->whereNumber('id');
        Route::get('/staging/{id}/attachments/{filename}', [TicketController::class, 'downloadStagingAttachment'])->name('staging.attachment.download')->whereNumber('id');
        Route::get('/staging/{id}/inline/{index}', [TicketController::class, 'serveStagingGraphInline'])->name('staging.graph.inline')->whereNumber(['id', 'index']);
        Route::get('/staging/{id}/graph-attachment/{index}', [TicketController::class, 'serveStagingGraphDownload'])->name('staging.graph.download')->whereNumber(['id', 'index']);
        Route::get('/staging-image/{id}/{filename}', [TicketController::class, 'serveStagingImage'])->name('staging.image.serve')->whereNumber('id');
        Route::get('/pending', [TicketController::class, 'pendingPage'])->name('pending');
        Route::get('/{id}/messages', [TicketController::class, 'getMessages'])->name('messages')->whereNumber('id');
        Route::post('/{id}/comment', [TicketController::class, 'addComment'])->name('comment')->whereNumber('id');

    });
    
    // ==================== CUSTOMER PORTAL ====================
    Route::prefix('my')->name('my.')->group(function () {
        Route::get('/tickets', [TicketController::class, 'myTickets'])->name('tickets');
        Route::get('/tickets/{id}', [TicketController::class, 'showMyTicket'])->name('tickets.show')->whereNumber('id');
    });

    // ==================== SETTINGS ====================
    Route::get('/settings', [SettingsController::class, 'index'])->name('settings');
    Route::post('/settings/preferences', [SettingsController::class, 'updatePreferences'])->name('settings.preferences');
    Route::post('/settings/reset', [SettingsController::class, 'resetPreferences'])->name('settings.reset');

    // ==================== PROFILE ====================
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile');
    Route::post('/profile/send-reset-link', [ProfileController::class, 'sendResetLink'])->name('profile.send-reset-link');

    // ==================== ATTACHMENTS (Graph proxy) ====================
    Route::get('/attachments/{id}', [AttachmentController::class, 'show'])->name('attachments.show')->whereNumber('id');

    // ==================== CUSTOMER PROFILE API (proxy → EcoSystem) ====================
    // Mirrors EcoSystem's /api/customers/{id}/... routes for profile section tabs.
    // Each endpoint authorizes that session customer_id == URL customer_id before proxying.
    Route::prefix('api/customers/{customerId}')->whereNumber('customerId')->group(function () {
        Route::get('/contacts',                    [CustomerApiController::class, 'contacts']);
        Route::get('/contacts/{contactId}',        [CustomerApiController::class, 'contact'])->whereNumber('contactId');
        Route::get('/addresses',                   [CustomerApiController::class, 'addresses']);
        Route::get('/addresses/{addressId}',       [CustomerApiController::class, 'address'])->whereNumber('addressId');
        Route::get('/identifications',             [CustomerApiController::class, 'identifications']);
        Route::get('/identifications/{identId}',   [CustomerApiController::class, 'identification'])->whereNumber('identId');
        Route::get('/banks',                       [CustomerApiController::class, 'banks']);
        Route::get('/banks/{bankId}',              [CustomerApiController::class, 'bank'])->whereNumber('bankId');
        Route::get('/attachments',                 [CustomerApiController::class, 'attachments']);
        Route::get('/attachments/{attachmentId}',  [CustomerApiController::class, 'attachment'])->whereNumber('attachmentId');
    });

});

// ==================== FALLBACK ====================
Route::fallback(function () {
    abort(404);
});